spring:
  datasource:
    url: ${DATABASE_URL}                     # ← WAJIB PAKAI INI DI RAILWAY
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect   # ← tambahkan ini
    hibernate:
      ddl-auto: update
    show-sql: true

  security:
    user:
      name: admin
      password: admin

jwt:
  secret: ${JWT_SECRET:rahasia123}

server:
  port: 8081