spring:
  datasource:
    url: jdbc:postgresql://${POSTGRES_HOST}:${POSTGRES_PORT}/${POSTGRES_DB}
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect  # Tambahkan ini biar Hibernate langsung kenal PostgreSQL
    hibernate:
      ddl-auto: update
    show-sql: false  # Ubah jadi false biar log bersih

  jwt:
    secret: ${JWT_SECRET:rahasia123}

server:
  port: 8081  # 8082 untuk transaction-service
