spring:
  datasource:
    url: jdbc:${DATABASE_URL}   # satu baris ini cukup, pasti jalan!
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update

jwt:
  secret: ${JWT_SECRET:rahasia123}

server:
  port: ${PORT:8081}