spring:
  datasource:
    url: jdbc:${DATABASE_URL}        # ‚Üê ini satu-satunya yang pasti ada di Railway
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.PostgreSQLDialect

jwt:
  secret: ${JWT_SECRET:rahasia123}

server:
  port: ${PORT:8081}   # Railway suka set PORT sendiri